module.exports = {
    FAHRENHEIT: 'f',
    CELCIUS: 'c',
    KELVIN: 'k',

    KILOMETERS: 'km/h',
    MILES: 'mi/h',
    METERS: 'm/s',

    YAHOO: 'yahoo',
    OPENWEATHERMAP: 'openweathermap',
    YRNO: 'yrno',
    FORECASTIO: 'forecastio',

    CLEAR: 'clear',
    CLOUDY: 'cloudy',
    FOG: 'fog',
    LIGHT_RAIN: 'light rain',
    RAIN: 'rain',
    THUNDERSTORM: 'thunderstorm',
    SNOW: 'snow',
    HAIL: 'hail',
    WIND: 'wind',
    EXTREME_WIND: 'extreme wind',
    TORNADO: 'tornado',
    HURRICANE: 'hurricane',
    EXTREME_COLD: 'extreme cold',
    EXTREME_HEAT: 'extreme cold',
    SNOW_THUNDERSTORM: 'snow thunderstorm',
};
